//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UploadTransaction_System.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionData
    {
        public string FileId { get; set; }
        public string TransactionId { get; set; }
        public Nullable<double> Amount { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Status { get; set; }
    }
}
